name: docker-example

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build docker image
        run: docker build -t ex3-docker-app ./ex3-docker

      - name: Execute docker image
        run: |
          docker run -d -p 5000:5000 ex3-docker-app
          sleep 10
          docker stop $(docker ps -q)
