name: pyenv poetry example

on:
  push:
    branches:
      - '*'

jobs:
  check-and-build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install python build tools
        shell: bash
        run: |
          sudo apt-get update -y
          sudo apt-get install -y make build-essential libssl-dev zlib1g-dev \
          libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libmariadb-dev \
          libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev ffmpeg

      - name: Install pyenv
        shell: bash
        run: |
          git clone https://github.com/pyenv/pyenv.git "$HOME/.pyenv"
          cd $HOME/.pyenv
          git checkout f50b99265c3abd72064f2ea5f4f6ae583e8f3688

      - name: Setup environment variables
        shell: bash
        run: |
          PYENV_ROOT="$HOME/.pyenv"
          PYENV_BIN="$PYENV_ROOT/bin"
          echo "$PYENV_BIN" >> $GITHUB_PATH
          echo "PYENV_ROOT=$PYENV_ROOT" >> $GITHUB_ENV

      - name: Check pyenv version
        shell: bash
        run: |
          pyenv --version

      - name: Install Poetry
        shell: bash
        run: |
          curl -sSL https://install.python-poetry.org | POETRY_VERSION=1.7.0 python -

      - name: Check poetry version
        shell: bash
        run: |
          poetry --version

      - name: Set up Python environment with Pyenv and Poetry
        shell: bash
        run: |
          cd ex5-pyenv-poetry
          pyenv install 3.10.12
          pyenv local 3.10.12
          poetry env use 3.10.12
          poetry install --no-root

      - name: Check code style
        run: |
          cd ex5-pyenv-poetry
          poetry run pre-commit run --all-files

      - name: Check code security
        run: |
          cd ex5-pyenv-poetry
          poetry run bandit -r .
